services:
  thirdparty:
    build: ./thirdpartymock
    ports:
      - "3000:3000"

  # client:
  #   build: ./client
  #   environment:
  #     YOUR_API: "http://api:3200"
  #   ports:
  #     - "3100:3100"

  api:
    build: ./your_api
    environment:
      PORT: "3200"
      WEBHOOK_URL: "http://api:3200"
      THIRD_PARTY: "http://thirdparty:3000"
      DATABASE_URL: "postgresql://docker:dontUseThisPassword@db:5432/api_db?schema=public"
      REDIS_HOST: "redis"
    ports:
      - "3200:3200"

  db:
    build: ./db
    environment:
      POSTGRES_USER: "docker"
      POSTGRES_DB: "api_db"
      POSTGRES_PASSWORD: "dontUseThisPassword"
    ports:
      - "5432:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"  
