CREATE USER docker with encrypted password 'dontUseThisPassword';

CREATE DATABASE api_db;

GRANT ALL PRIVILEGES ON DATABASE api_db TO docker;

CREATE TABLE transactions (
	id 			integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	amount		integer,
	status		integer,
	created_at	date,
	updated_at	date
);